// Phase 2 Plan 02-02 Task 2 — calcPrice tool (MATCH-03, MATCH-05).
//
// CONTEXT D-24..D-27. Source: 02-RESEARCH.md §5 (calcPrice pure function VERBATIM)
// + price-lock helper for D-25.
//
// Key invariants:
//   - `calcPrice` is PURE — no I/O, no LLM call. Same input → same output forever.
//   - Returns `{default, min, max, breakdown}` bigint kopecks. Corridor:
//       min = roundTo50(default × 0.85)
//       max = roundTo50(default × 1.15)
//   - Pipeline writes `leads.quoted_price = default` BEFORE assembling a reply.
//     The reply is built by template substitution, NOT generated by the LLM
//     (Pitfall #1 closure at the code level).
//   - The tool registration calls `readPricingConfig(db)` lazily at run-time so
//     the pure `calcPrice` function stays independent of DB state.

import { betaZodTool } from '@anthropic-ai/sdk/helpers/beta/zod';
import { sql } from 'drizzle-orm';
import { z } from 'zod/v4';
import type { Db } from '../../db.js';
import { roundTo50Rubles } from '../../lib/money.js';
import type { ToolContext } from './index.js';

export interface PricingConfig {
  rate_per_km_kopecks: bigint;
  dir_coef: Record<'default' | 'back_haul', number>;
  season_coef: (date: Date) => number;
}

export interface CalcPriceInput {
  route_km: number;
  tons: number;
  bodyType: 'tent' | 'ref' | 'iso' | 'container';
  date: Date;
  direction: 'default' | 'back_haul';
}

export interface CalcPriceOutput {
  default: bigint; // → leads.quoted_price (D-25)
  min: bigint; // floor for `discount` tool (D-26)
  max: bigint; // surge ceiling
  breakdown: {
    base_kopecks: bigint;
    dir_factor: number;
    season_factor: number;
  };
}

/**
 * Pure deterministic price calculator. Same inputs → same outputs across runs.
 *
 * Formula (D-24, RESEARCH.md §5 VERBATIM):
 *   base       = round_half(route_km × rate_per_km_kopecks)
 *   adjusted   = round_half(base × dir_coef[direction] × season_coef(date))
 *   default    = roundTo50Rubles(adjusted)
 *   min        = roundTo50Rubles(adjusted × 0.85)
 *   max        = roundTo50Rubles(adjusted × 1.15)
 *
 * `route_km` is a float; multiplication happens in number-space, then converted
 * to bigint via Math.round so the result is a discrete kopecks integer.
 */
export function calcPrice(input: CalcPriceInput, cfg: PricingConfig): CalcPriceOutput {
  const baseFloat = input.route_km * Number(cfg.rate_per_km_kopecks);
  const baseRoundedKop = BigInt(Math.round(baseFloat));
  const dir = cfg.dir_coef[input.direction];
  const season = cfg.season_coef(input.date);
  const adjustedFloat = Number(baseRoundedKop) * dir * season;
  const adjustedKop = BigInt(Math.round(adjustedFloat));
  const defaultKop = roundTo50Rubles(adjustedKop);
  const minKop = roundTo50Rubles(BigInt(Math.round(Number(adjustedKop) * 0.85)));
  const maxKop = roundTo50Rubles(BigInt(Math.round(Number(adjustedKop) * 1.15)));
  return {
    default: defaultKop,
    min: minKop,
    max: maxKop,
    breakdown: {
      base_kopecks: baseRoundedKop,
      dir_factor: dir,
      season_factor: season,
    },
  };
}

/**
 * Read pricing_config from the DB and assemble a PricingConfig.
 *
 * Phase 1 seeded three rows: rate_per_km (number), dir_coef (object),
 * season_coef (number). The function tolerates missing keys by falling back
 * to demo defaults — production should fail-fast, but Phase 2 keeps it
 * forgiving while the seed runner stabilises.
 */
export async function readPricingConfig(db: Db): Promise<PricingConfig> {
  const result = await db.execute(sql`
    SELECT key, value FROM pricing_config
    WHERE key IN ('rate_per_km', 'dir_coef', 'season_coef')
  `);
  const map = new Map<string, unknown>();
  for (const r of result.rows as Array<{ key: string; value: unknown }>) {
    map.set(r.key, r.value);
  }
  const ratePerKm = map.get('rate_per_km');
  const dirCoefVal = map.get('dir_coef');
  const seasonCoefVal = map.get('season_coef');
  if (typeof ratePerKm !== 'number') {
    throw new Error(
      `pricing_config.rate_per_km expected number, got ${typeof ratePerKm} (${JSON.stringify(ratePerKm)})`
    );
  }
  const dirCoef =
    typeof dirCoefVal === 'object' && dirCoefVal !== null
      ? (dirCoefVal as PricingConfig['dir_coef'])
      : { default: 1.0, back_haul: 0.85 };
  const seasonNum = typeof seasonCoefVal === 'number' ? seasonCoefVal : 1.0;
  return {
    rate_per_km_kopecks: BigInt(Math.round(ratePerKm)),
    dir_coef: dirCoef,
    season_coef: () => seasonNum, // future: date-dependent coefficient
  };
}

export const CalcPriceInputSchema = z.object({
  route_km: z.number().positive(),
  tons: z.number().positive(),
  body_type: z.enum(['tent', 'ref', 'iso', 'container']),
  direction: z.enum(['default', 'back_haul']).default('default'),
});

export function calcPriceTool(ctx: ToolContext) {
  return betaZodTool({
    name: 'calcPrice',
    description:
      'Calculate the price corridor {min, default, max} for a route. Deterministic. NEVER quote the result to the client directly — the pipeline writes `default` to leads.quoted_price and renders it via a template.',
    inputSchema: CalcPriceInputSchema,
    run: async (input) => {
      // Belt-and-suspenders re-validation per D-05.
      CalcPriceInputSchema.parse(input);
      const cfg = await readPricingConfig(ctx.db);
      const out = calcPrice(
        {
          route_km: input.route_km,
          tons: input.tons,
          bodyType: input.body_type,
          date: new Date(),
          direction: input.direction,
        },
        cfg
      );
      ctx.log.info(
        {
          tool: 'calcPrice',
          leadId: ctx.leadId,
          default_kopecks: out.default.toString(),
        },
        'tool.invoked'
      );
      // bigint → string for JSON-safe envelope.
      return JSON.stringify({
        ok: true,
        data: {
          default: out.default.toString(),
          min: out.min.toString(),
          max: out.max.toString(),
          breakdown: {
            base_kopecks: out.breakdown.base_kopecks.toString(),
            dir_factor: out.breakdown.dir_factor,
            season_factor: out.breakdown.season_factor,
          },
        },
      });
    },
  });
}
